#!/bin/sh

TITLE=""
if [ -e "$1.title" ]; then
	TITLE=`cat $1.title`
fi

cat << EOF
<html>
<head>
<style type="text/css">
#gipfel { display: block; position: relative; margin: 0; padding: 0; }
#gipfel li { visibility: hidden; list-style-type: none; position: absolute; background: url(25w.png); border: 1px solid black; font-family: sans-serif; font-size: x-small; color: #000; padding: 0; line-height: 1.3em; overflow: hidden; }
#gipfel span { visibility: hidden; position: absolute; left: 0; right: 0; display: block; padding: 5px; }
#gipfel:hover li { visibility: visible; }
#gipfel li:hover span {visibility: visible;}
EOF

i=0
grep -v "^#" gipfelweb/gipfel/${1}.gipf | \
while read name height x y dist flags dummy; do
	if [ "${flags}" = "HIDDEN" ]; then
		continue
	fi

	thumb_w=`identify -format %w gipfelweb/thumbs/${name}`
	thumb_h=`identify -format %h gipfelweb/thumbs/${name}`

	echo "#id_${i} {left:$((${x} - 20 / 2))px; top: $((${y} - 20 / 2))px; width: 20px; height: 20px;}"
	echo "#id_${i}:hover {width: ${thumb_w}px; height: ${thumb_h}px; background: url(thumbs/${name});}"

	i=$((${i} + 1))
done

cat << EOF
</style></head>
<body bgcolor="#919faa">
<script type="text/javascript"><!--
google_ad_client = "pub-4715934322518147";
google_ad_width = 728;
google_ad_height = 90;
google_ad_format = "728x90_as";
google_ad_type = "text_image";
google_ad_channel = "";
google_color_border = "ffffff";
google_color_bg = "f3f3f3";
google_color_link = "000000";
google_color_text = "333333";
google_color_url = "666666";
--></script><script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js"></script>
<br/>
<br/>
EOF

echo "<h3>$TITLE</h3>"

cat << EOF
<table border="0" cellpadding="0" cellspacing="1" width="542" bgcolor="black">
<tr><td>
<table border="0" cellpadding="10" cellspacing="0" width="542" bgcolor="white">
<tr><td>
<div id="gipfel">
EOF

echo "<img src=\"slides/${1}.jpg\"/>"

i=0
grep -v "^#" gipfelweb/gipfel/${1}.gipf | \
while read name height x y dist flags dummy; do
	if [ "${flags}" = "HIDDEN" ]; then
		continue
	fi

	THUMB_TITLE="${name%.jpg}"
	if [ -e "${name%.jpg}.title" ]; then
		THUMB_TITLE=`cat ${name%.jpg}.title`
	fi

	echo "<li id=\"id_${i}\"><a href=\"${name%.jpg}.html\"><span>${THUMB_TITLE} (${height}m)</span></a></li>"

	i=$((${i} + 1))
done

cat << EOF
</ul>
</div>
</td></tr>
</table>
</td></tr>
</table>
<small>copyright &copy; 2007 <ahref="http://www.ecademix.com/JohannesHofmann/impressum.html">Johannes Hofmann</a></small>
</body>
</html>
EOF
