#!/bin/sh

MODE="$1"
TITLE="$2"
FILE="$3"

if [ "$MODE" = "images" ]; then
	DATAFILE="gipfelweb/gipfel/${FILE}.imgs"
else
	DATAFILE="gipfelweb/gipfel/${FILE}.hills"
fi

cat << EOF
<html>
<head>
<style type="text/css">
#gipfel { display: block; position: relative; margin: 0; padding: 0; }
#gipfel li { visibility: hidden; list-style-type: none; position: absolute; background: url(25w.png); border: 1px solid black; font-family: sans-serif; font-size: x-small; color: #000; padding: 0; line-height: 1.3em; overflow: hidden; }
#gipfel span { visibility: hidden; position: absolute; left: 0; right: 0; display: block; padding: 5px; }
#gipfel:hover li { visibility: visible; }
#gipfel li:hover span {visibility: visible;}
EOF

IFS="	"
i=0
grep -v "^#" ${DATAFILE} | \
while read name height x y dist flags dummy; do
	if [ "${flags}" = "HIDDEN" ]; then
		continue
	fi

	if [ "$MODE" = "images" ]; then
		thumb_w=`identify -format %w gipfelweb/thumbs/${name}`
		thumb_h=`identify -format %h gipfelweb/thumbs/${name}`

		echo "#id_${i} {left:$((${x} - 10 / 2))px; top: $((${y} - 6 / 2))px; width: 10px; height: 6px;}"
		echo "#id_${i}:hover {width: ${thumb_w}px; height: ${thumb_h}px; background: url(thumbs/${name});}"
	else
		echo "#id_${i} {left:$((${x} - 4 / 2))px; top: $((${y} - 4 / 2))px; width: 4px; height: 4px;}"
		echo "#id_${i}:hover {width: 200px; height: 20px;}"
	fi

	i=$((${i} + 1))
done

cat << EOF
</style></head>
<body bgcolor="#919faa">
<script type="text/javascript"><!--
google_ad_client = "pub-4715934322518147";
google_ad_width = 728;
google_ad_height = 90;
google_ad_format = "728x90_as";
google_ad_type = "text_image";
google_ad_channel = "";
google_color_border = "ffffff";
google_color_bg = "f3f3f3";
google_color_link = "000000";
google_color_text = "333333";
google_color_url = "666666";
--></script><script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js"></script>
<br/>
<br/>
EOF

echo "<h3>$TITLE</h3>"

if [ "$MODE" = "images" ]; then
	echo "<a href=\"hills/${FILE}.html\">show hill names</a>"
else
	echo "<a href=\"javascript:history.back()\">back to gipfelweb</a>"
fi

cat << EOF
<table border="0" cellpadding="0" cellspacing="1" bgcolor="black">
<tr><td>
<table border="0" cellpadding="10" cellspacing="0" bgcolor="white">
<tr><td>
<div id="gipfel">
EOF

if [ "$MODE" = "images" ]; then
	echo "<img src=\"slides/${FILE}.jpg\"/>"
else
	echo "<img src=\"../slides/${FILE}.jpg\"/>"
fi

i=0
grep -v "^#" ${DATAFILE} | \
while read name height x y dist flags dummy; do
	if [ "${flags}" = "HIDDEN" ]; then
		continue
	fi

	if [ "$MODE" = "images" ]; then
		THUMB_TITLE="${name%.jpg}"
		if [ -e "${name%.jpg}.title" ]; then
			THUMB_TITLE=`cat ${name%.jpg}.title`
		fi
		echo "<li id=\"id_${i}\"><a href=\"${name%.jpg}.html\"><span>${THUMB_TITLE} (${height}m)</span></a></li>"
	else
		echo "<li id=\"id_${i}\"><span>${name} (${height}m)</span></li>"
	fi

	i=$((${i} + 1))
done

cat << EOF
</ul>
</div>
</td></tr>
</table>
</td></tr>
</table>
<small>copyright &copy; 2007 <ahref="http://www.ecademix.com/JohannesHofmann/impressum.html">Johannes Hofmann</a></small>
</body>
</html>
EOF
