all: ProjectionRectilinear_funcs.cxx ProjectionCylindrical_funcs.cxx

ProjectionRectilinear_funcs.cxx: lsq_rectilinear.mac expr2c.mac
	maxima -b lsq_rectilinear.mac | grep "^double" > ProjectionRectilinear_funcs.cxx

ProjectionCylindrical_funcs.cxx: lsq_cylindrical.mac expr2c.mac
	maxima -b lsq_cylindrical.mac | grep "^double" > ProjectionCylindrical_funcs.cxx
